name: pet_battle_royale
description: A real-time multiplayer pet battle game built with Flutter and Flame.
publish_to: 'none'

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # 🔥 Core Game Engine
  audioplayers: ^6.5.0
  flame: ^1.16.0
  flame_audio: ^2.11.6  # ✅ Latest compatible audio for Flame 1.16

  # 🔥 Firebase Integration
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9

  # 🎨 UI and Effects
  lottie: ^3.3.1
  shared_preferences: ^2.2.2
  flame_lottie: ^0.4.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/pets/
    - assets/lottie/
