// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1MTTRTp4RHkRJGIXFJIBwM_RcAYHC4rY',
    appId: '1:827099706765:web:6324fa5986e0f11f9139c4',
    messagingSenderId: '827099706765',
    projectId: 'lx21-67bda',
    authDomain: 'lx21-67bda.firebaseapp.com',
    storageBucket: 'lx21-67bda.firebasestorage.app',
    measurementId: 'G-ZF2ZCXGRX4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3Nm_5No3jFf2gco3ac0TRUYsKCFei2m0',
    appId: '1:827099706765:android:384b8da24326a70d9139c4',
    messagingSenderId: '827099706765',
    projectId: 'lx21-67bda',
    storageBucket: 'lx21-67bda.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy4PC-pcLdkhXk9v3wI3l4tnbRXhaQHs0',
    appId: '1:827099706765:ios:36698a73f588346a9139c4',
    messagingSenderId: '827099706765',
    projectId: 'lx21-67bda',
    storageBucket: 'lx21-67bda.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBy4PC-pcLdkhXk9v3wI3l4tnbRXhaQHs0',
    appId: '1:827099706765:ios:36698a73f588346a9139c4',
    messagingSenderId: '827099706765',
    projectId: 'lx21-67bda',
    storageBucket: 'lx21-67bda.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1MTTRTp4RHkRJGIXFJIBwM_RcAYHC4rY',
    appId: '1:827099706765:web:b65027177206815c9139c4',
    messagingSenderId: '827099706765',
    projectId: 'lx21-67bda',
    authDomain: 'lx21-67bda.firebaseapp.com',
    storageBucket: 'lx21-67bda.firebasestorage.app',
    measurementId: 'G-KW0KRPRLEK',
  );
}
